version: '3.8'

services:
  jenkins:
    build:
      context: dockerfile
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8888:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    user: "${UID}:${GID}"

volumes:
  jenkins_home:
    driver: local
